### ISSUE TITLE
vanguard-api: issue with register() function in api.py

### ISSUE THREAD

**Issue by crimsonvulture** [rikonor/vanguard-api#1]
Within the register function in api.py, the variables username, email, and password are referenced on line 48; however, these variables do not exist in the current scope:

48      Users.register_user(username, email, password)

The line should read (or something of the same effect):

48      Users.register_user(params["username"], params["email"], params["password"])

**Comment by rikonor** [comment]
Hi @crimsonvulture,

Thanks for submitting the issue. Although it seems like a simple fix, I won't have time to test this in the next few days. If you'd be willing to put in the fix in a PR and run some tests on your end, I'd be happy to merge it for you.

Best,
Or

**Comment by rikonor** [comment]
Closing as this was fixed in https://github.com/rikonor/vanguard-api/pull/2
